### ISSUE TITLE
CodeOptimizationCodeFixProvider 触发异常

### ISSUE THREAD

**Issue by xbotter** [TimChen44/CCodeAI#14]
'CodeOptimizationCodeFixProvider' encountered an error and has been disabled.

版本：2023.514.1 

AppKey 已经设置过了
![image](https://github.com/TimChen44/CCodeAI/assets/3634877/059623f0-cb14-47f7-8e0f-47af19369e05)

错误截图。
![image](https://github.com/TimChen44/CCodeAI/assets/3634877/7d1b6ef5-3d3b-40fa-acb0-b579b6c8e0f0)
错误栈：
```log
Microsoft.SemanticKernel.Diagnostics.ValidationException : NullValue: The Azure endpoint cannot be empty
   at Microsoft.SemanticKernel.Diagnostics.Verify.ThrowValidationException(ErrorCodes errorCodes,String message)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.AzureOpenAIClientBase..ctor(String modelId,String endpoint,String apiKey,IDelegatingHandlerFactory handlerFactory,ILogger log)
   at Microsoft.SemanticKernel.KernelConfigOpenAIExtensions.<>c__DisplayClass3_0.<AddAzureTextEmbeddingGenerationService>g__Factory|0(IKernel kernel)
   at Microsoft.SemanticKernel.Kernel.GetService[T](String name)
   at Microsoft.SemanticKernel.MemoryConfiguration.UseMemory(IKernel kernel,String embeddingsServiceId,IMemoryStore storage)
   at Microsoft.SemanticKernel.KernelBuilder.Build()
   at KernelFactory.Init()
   at async KernelFactory.InvokeCodeFuncationAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async CCodeAI.QuickActions.CodeOptimizationCodeFixProvider.OptimizeCode(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.PreviewChangesSuggestedAction.CreateAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.GetPreviewChangesFlavorAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.CreateAllFlavorsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by weianweigan** [comment]
It seems a error from semantic kernel when checking auzre openai endpoint.

**Comment by weianweigan** [comment]
I got this error too and I have not set the key.

![image](https://github.com/TimChen44/CCodeAI/assets/25452811/5995aa5c-608c-47a4-8ad7-24d4d37e95aa)
